#!/usr/bin/env sh

[ -f ~/.xprofile ] && . ~/.xprofile
#exec i3
xrdb ~/.Xresources
exec startdwm


#feh --bg-scale /home/lars/pictures/Wallpaper/Wallpaper.jpg&
#compton &

#dunst&
#setxkbmap -layout de&
#sxhkd &
#unclutter 
#exec startdwm
