#!/bin/sh

# Refresh the dwmbar.
# Send SIGTRAP signal to dwmbar script, which will handle it with a trap.
pkill -SIGTRAP dwmbar
#kill "$(pstree -p | grep -- -dwmbar\([0-9]| sed "s/.*sleep(\([0-9]\+\)).*/\]/")"9
